name = "jmeter-test-demo"
workers_dev = false
main = "src/index.js"
compatibility_date = "2024-09-23"
assets = { directory = "./static", binding = "ASSETS" }

[vars]
SITE_ACCESS_CHALLENGE_EVERY_VISIT = "true"

# Bind the D1 database
[[d1_databases]]
binding = "DB"
database_name = "jmeter-test-demo"
database_id = "c753aa63-5146-45b1-adca-bd5f3ff89f09"

# Custom domain route (already configured in the Cloudflare UI; this keeps Wrangler in sync)
[[routes]]
pattern = "private.loadmagic.ai"
custom_domain = true
